language: java
jdk:
  - oraclejdk8
before_script:
  - cd server
  - chmod +x gradlew
script:
  # Run tests when not on coverity branch.
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      ./gradlew check;
    fi
cache:
  directories:
  - ~/.gradle
after_success:
  # Upload coveralls when not on coverity branch.
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
      ./gradlew cobertura coveralls;
    fi
notifications:
  email:
    on_success: change
env:
  - TERM=dumb
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "ZVjOV33nVIUC8ftmV9qGjnAq+JgI2ca809KXCz7RZmfCRDOO61rcwB+mVnmnPKW/INWU5SmRLKjGcNPNzv8Mcoprz/yUS7ynepIgFt07WGkhGP9euB7E+RDiTpO3Jb4E0+cpUZnpI/pwoQoPw5uiHTj4WjqXXRSd9l1TJ8pun+pa3Pe/iXvF2Ip3/L8ofjLN8SlETHsPTTthin89F09JZhTCEVkn9lNHXStve13Sz42nHz5Fb7S4T8nv13ZgrTh1/b/5Zt9GIm71zxlFC+AM8ph/Dx3B6koYU9O2CjeIHJwtuJVib4xt4v583IHnqvqGL69H8Zx6ETCHOOQpDLssDuOUqxsVC/aIbMiEzzJnTC4bRzQ8nyOnrTkYOVIV313at3zNbeL7fbA2Kx6LF/8mDs+xOaTvh8JQayjldq7/kiXpwxjyH8ha1RDlBiDUDfHVxX0/YK35yLzCzJlGr5KcM8BPMvRmiVBnlvIeCevRzcEgWyWC0NSjoT2Bnkt5FgLOQI55Q+/yz3kC0qtpWt7pSK9j5WOc3cIS7MqoTLFOV2lJggI+Btp7fbIQoCfQ0JUuwLnSZMo+em0qAj1XmkTQWtgOiIkJ/U8tobtyJQnws43gnsKW+sSQZkrJxlRDJXDltxizJejsDMtpfCOyKCaKIVUq8BAmGt06FNDc4d89wec="
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "Edvinas01/chat-rooms"
      description: "Build submitted via Travis CI"
    notification_email: edvinas108@gmail.com
    build_command_prepend: ""
    build_command: "./gradlew build"
    branch_pattern: coverity_scan