language: java
jdk:
  - oraclejdk8
before_script:
  - cd server
  - chmod +x gradlew
script:
  - ./gradlew wrapper
cache:
  directories:
  - ~/.gradle
after_success:
  - ./gradlew cobertura coveralls
notifications:
  email:
    on_success: change