facebook:
  details:
    type: facebook
    path: /login/facebook
  client:
    client-id: secret
    client-secret: secret
    access-token-uri: https://graph.facebook.com/oauth/access_token
    user-authorization-uri: https://www.facebook.com/dialog/oauth
    token-username: oauth_token
    authentication-scheme: query
    client-authentication-scheme: form
  resource:
    user-info-uri: https://graph.facebook.com/me