logging:
  level:
    com.edd.chat: debug
server:
  port: 10000
spring.data.mongodb.uri: mongodb://10.10.30.30:27017/test

# App specific configuration.
chat:
  auth:
    token:
      secret: secret
      # Token expiration in hours
      expiration: 24
  max.comments: 1000
  channels.main: General

---

# Use embedded mongodb configuration in tests.
spring:
  profiles: test
  data.mongodb.uri: mongodb://localhost/test